run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - web
    - test/e2e
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
